# From:
# https://www.docker.com/blog/docker-github-actions/
# https://github.com/metcalfc/docker-action-examples

name: Docker-Build

on:
  push:
    tags:
      - "*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Dockerfile
        uses: ./.github/actions/validate-dockerfile

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./docker
          file: ./docker/Dockerfile
          build-args: |
            COMPOSER_REQUIRE_VERSION=${{ steps.get_version.outputs.VERSION }}
          push: true
          tags: ghcr.io/${{ github.repository }}:latest,ghcr.io/${{ github.repository }}:${{ steps.get_version.outputs.VERSION }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
